### ISSUE TITLE
Multiple Files Support

### ISSUE THREAD

**Issue by vednig** [doshareme/src#3]

**Comment by vednig** [comment]
@yinkaenoch

**Comment by YinkaEnoch** [comment]
My plan is to zip multiple files together into a single zip file and then upload the zipped blob. The zipped file can then be downloaded and unzipped by the user

**Comment by YinkaEnoch** [comment]
https://github.com/doshareme/src/pull/17

**Comment by vednig** [comment]
Closing this. Congrats to @YinkaEnoch 🎉 for your first approved PR
